apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: api-gateway
build:
  artifacts:
    - image: ghcr.io/abhirambsn/pbl-api-gateway
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/dev-k8s.yml
