apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: discovery-server
build:
  artifacts:
    - image: ghcr.io/abhirambsn/pbl-discovery-server
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/dev-k8s.yml
