services:
  postgres:
    image: postgres:15.5
    ports:
      - "5432:5432"
    env_file:
      - ./.env.postgres
  
  mongodb:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=rag
    ports:
      - "27017:27017"
volumes:
  mongo_data: