apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-api-deployment
  namespace: pbl
  labels:
    app: chat-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-api
  template:
    metadata:
      labels:
        app: chat-api
    spec:
      containers:
      - name: chat-api-container
        image: ghcr.io/abhirambsn/pbl-chat-api:latest
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "docker"
          - name: EUREKA_USERNAME
            value: "eureka"
          - name: EUREKA_PASSWORD
            value: "password"
          - name: MONGO_USERNAME
            value: "admin"
          - name: MONGO_PASSWORD
            value: "admin"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: chat-api
  namespace: pbl
spec:
  type: ClusterIP
  selector:
    app: chat-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
