apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-api-deployment
  labels:
    app: rag-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-api
  template:
    metadata:
      labels:
        app: rag-api
    spec:
      containers:
      - name: rag-api-container
        image: ghcr.io/abhirambsn/pbl-rag-api:latest
        env:
          - name: PG_DB_URL
            valueFrom:
              secretKeyRef:
                name: pg-db-url
                key: pg-db-url
          - name: EUREKA_SERVER
            valueFrom:
              secretKeyRef:
                name: eureka-server
                key: eureka-server
          - name: BOT_SOCKET_URL
            value: "ws://rag-chatbot:8000/ws"
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: rag-logs-storage
          mountPath: /.logs
      volumes:
      - name: rag-logs-storage
        persistentVolumeClaim:
          claimName: rag-logs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: rag-api
spec:
  type: ClusterIP
  selector:
    app: rag-api
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
