# Keycloak Deployment and Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
      - name: keycloak
        image: ghcr.io/abhirambsn/pbl-keycloak:latest
        command: 
          - "/opt/keycloak/bin/kc.sh"
          - "start"
          - "--hostname"
          - "https://keycloak.localhost.localstack.cloud:8081"
          - "--hostname-backchannel-dynamic"
          - "true"
        ports:
        - containerPort: 8080
        - containerPort: 8443
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "change_me"
        - name: KC_DB
          value: "postgres"
        - name: KC_DB_URL
          value: "jdbc:postgresql://postgres/rag"
        - name: KC_DB_USERNAME
          value: "dev-postgres"
        - name: KC_DB_PASSWORD
          value: "dev-postgres"
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_HEALTH_ENABLED
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  type: ClusterIP
  selector:
    app: keycloak
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
  - protocol: TCP
    port: 8443
    targetPort: 8443
    name: https
