apiVersion: apps/v1
kind: Deployment
metadata:
  name: convobot-ui-app-deployment
  namespace: pbl
  labels:
    app: convot-ui-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: convot-ui-app
  template:
    metadata:
      labels:
        app: convot-ui-app
    spec:
      containers:
      - name: convot-ui-app
        image: pbl-ui:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: convot-ui-app-service
  namespace: pbl
spec:
  selector:
    app: convot-ui-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer