name: pbl-prod
services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "9000:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  watchtower: 
    image: containrrr/watchtower
    container_name: watchtower
    command: --interval 30 --label-enable --rolling-restart
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
  mongodb:
    image: mongo:6
    container_name: mongodb-prod
    volumes:
      - mongo_data:/data/db
    environment:
      - ./envs/.mongo.env
    ports:
      - "27017:27017"
  
  postgres:
    image: postgres:15.5
    container_name: postgresql-prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./envs/.pg.env

  discovery-server:
    image: ghcr.io/abhirambsn/pbl-discovery-server:prod
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - ../.logs:/.logs
    env_file:
      - ./envs/.common.env
  
  profile-api:
    image: ghcr.io/abhirambsn/pbl-profile-api:prod
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    env_file:
      - ./envs/.common.env
    volumes:
      - ../.logs:/.logs
    depends_on:
      - discovery-server
      - mongodb
  
  chat-api:
    image: ghcr.io/abhirambsn/pbl-chat-api:prod
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    env_file:
      - ./envs/.common.env
    volumes:
      - ../.logs:/.logs
    depends_on:
      - discovery-server
      - mongodb
  
  rag-api:
    image: ghcr.io/abhirambsn/pbl-rag-api:prod
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    env_file:
      - ./envs/.common.env
    volumes:
      - ../.logs:/.logs
    depends_on:
      - discovery-server
      - mongodb
  
  keycloak:
    build:
      context: .
      dockerfile: ./Dockerfile.keycloak
    container_name: keycloak-prod
    command: start --hostname http://localhost:8080 --hostname-backchannel-dynamic true --optimized
    env_file:
      - ./envs/.kc.env
    ports:
      - 8080:8080
    restart: always
    volumes:
      - keycloak_data:/data
    depends_on:
      - postgres
  
  api-gateway:
    image: ghcr.io/abhirambsn/pbl-api-gateway:prod
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.routers.api-gateway.rule=Host(`localhost`)"
      - "traefik.enable=true"
    env_file:
      - ./envs/.common.env
    volumes:
      - ../.logs:/.logs
    depends_on:
      - reverse-proxy
      - discovery-server
      - profile-api
      - chat-api
      - rag-api
      - keycloak
    deploy:
      mode: replicated
      replicas: 2

volumes:
  mongo_data:
  keycloak_data:
  postgres_data: