apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: rag-api
build:
  artifacts:
    - image: ghcr.io/abhirambsn/pbl-rag-api
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/dev-k8s.yml
