apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-chatbot-deployment
  labels:
    app: rag-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-chatbot
  template:
    metadata:
      labels:
        app: rag-chatbot
    spec:
      containers:
      - name: rag-chatbot-container
        image: ghcr.io/abhirambsn/pbl-rag-chatbot:latest
        env:
          - name: PINECONE_API_KEY
            valueFrom:
              secretKeyRef:
                name: pinecone-api-key
                key: pinecone-api-key
          - name: GOOGLE_API_KEY
            valueFrom:
              secretKeyRef:
                name: google-api-key
                key: google-api-key
          - name: CHAT_SERVICE_URL
            value: "http://chat-api:8080"
          - name: SQS_QUEUE_URL
            value: "http://queue:4100/100010001000/query-results"
          - name: AWS_ENDPOINT_URL
            value: "http://queue:4100"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: rag-chatbot
spec:
  type: ClusterIP
  selector:
    app: rag-chatbot
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
