apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-chatbot-deployment
  labels:
    app: rag-chatbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rag-chatbot
  template:
    metadata:
      labels:
        app: rag-chatbot
    spec:
      containers:
      - name: rag-chatbot-container
        image: ghcr.io/abhirambsn/pbl-rag-chatbot:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Pod
metadata:
  name: rag-chatbot-pod
  labels:
    app: rag-chatbot
spec:
  containers:
  - name: rag-chatbot-container
    image: ghcr.io/abhirambsn/pbl-rag-chatbot:latest
    ports:
    - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: rag-chatbot
spec:
  type: ClusterIP
  selector:
    app: rag-chatbot
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
