name: React UI CI
on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ui/**
  pull_request: 
    branches:
      - main
    paths:
      - ui/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        
        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20'

        - name: Cache Node.js modules
          uses: actions/cache@v3
          with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('ui/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-node-
        
        - name: Install dependencies
          working-directory: ui
          run: npm ci
        
        - name: Run Tests
          working-directory: ui
          run: npm test -- --watchAll=false
        
  docker-build:
    runs-on: ubuntu-latest
    needs: test

    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        
        - name: Login to Dockerhub
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        
        - name: Build and Push Docker Image
          uses: docker/build-push-action@v5
          with:
            context: ./ui
            file: ./ui/Dockerfile
            platforms: linux/amd64,linux/arm64
            push: true 
            tags: |
              ghcr.io/${{ github.actor }}/pbl-ui:latest
              ghcr.io/${{ github.actor }}/pbl-ui:${{ github.ref == 'refs/heads/main' && 'prod' || github.sha }}

        - name: Cache Docker layers
          uses: actions/cache@v4
          with:
            path: /tmp/.buildx-cache
            key: ${{ runner.os }}-buildx-${{ github.sha }}
            restore-keys: |
              ${{ runner.os }}-buildx-

        
      



