name: Build RAG API
on: 
  push:
    branches:
      - main
    paths:
      - rag-api/**
  pull_request: 
    branches:
      - main
    paths:
      - rag-api/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Pytest tests
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r rag-api/requirements.txt
        working-directory: ./rag-api
      
      - name: Run tests
        run: |
          pytest
        working-directory: ./rag-api
      
      - name: Cleanup
        run: |
          rm -rf __pycache__
          rm -rf .pytest_cache
        working-directory: ./rag-api
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and Push Docker image [rag-api]
        run: docker build --push --file ./rag-api/Dockerfile -t ${{ vars.DOCKER_USERNAME }}/pbl-rag-api:latest ./rag-api
    
