name: Build React UI
on: 
    push:
      branches:
        - main
      paths:
        - ui/**
    pull_request: 
      branches:
        - main
      paths:
        - ui/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        working-directory: ./ui

      - name: Run tests
        run: npm test
        working-directory: ./ui
    
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and Push Docker image [ui]
        run: docker build --push --file ./ui/Dockerfile -t ${{ vars.DOCKER_USERNAME }}/pbl-ui:latest ./ui
    
